---
- name: "[Ubuntu] Fail if release is not supported (ansible version < 2.5)"
  fail:
    msg="The role is designed only for Ubuntu 16.04"
  when:
    - ansible_version.minor < 5
      #    - ansible_distribution_version | version_compare('16.04', '!=')

      #- name: "[Ubuntu] Fail if release is not supported (ansible version >= 2.5)"
      #  fail:
      #    msg="The role is designed only for Ubuntu 16.04"
      #  when:
      #     - ansible_version.minor >= 5
      #     - ansible_distribution_version is version('16.04', '!=')

- name: "[Ubuntu] Import the Docker repository key"
  apt_key:
    url=https://download.docker.com/linux/ubuntu/gpg
    state=present
    id=0EBFCD88

- name: "[Ubuntu] Add docker apt repo"
  apt_repository:
    repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state=present

- name: "[Ubuntu] Force an apt cache refresh"
  apt: update_cache=yes
  changed_when: False

- name: "[Ubuntu] Perform common tasks"
  include: common.yml

